---
- name: template-service-broker-operator
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  roles:
  - role: template-service-broker
  vars:
    state: present
    broker_name: "{{ meta.name }}"
    broker_namespace: "{{ meta.namespace }}"
