apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: templateservicebrokeroperator.v0.1.0
  namespace: placeholder
spec:
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: template-service-broker-operator
        rules:
        - apiGroups:
          - openshift.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
      deployments:
      - name: template-service-broker-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: template-service-broker-operator
          template:
            metadata:
              labels:
                app: template-service-broker-operator
            spec:
              containers:
                - name: template-service-broker-operator-olm-owned
                  image: docker.io/eriknelson/template-service-broker-operator
                  imagePullPolicy: Always
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: template-service-broker-operator
              serviceAccount: template-service-broker-operator
  customresourcedefinitions:
    owned:
      - description: Represents an instance of a Template Service Broker
        displayName: Template Service Broker
        kind: TemplateServiceBroker
        name: templateservicebrokers.openshift.io
        version: 0.1.0
  version: 0.1.0
  displayName: Template Service Broker Operator
  labels:
    olm-owner-enterprise-app: template-service-broker-operator
    olm-status-descriptors: templateservicebrokeroperator.v0.1.0
