---
state: present

kube_system_namespace: kube-system
broker_namespace: openshift-template-service-broker
broker_image: docker.io/openshift/origin-template-service-broker:latest
broker_log_level: '0'
broker_node_selector: "{{ {'node-role.kubernetes.io/master':'true'} | to_json }}"
apiserver_service_name: apiserver
apiserver_serving_cert_secret : apiserver

template_namespaces: ['openshift']
