---
# to be able to expose TSB inside the cluster
apiVersion: v1
kind: Service
metadata:
  namespace: "{{ broker_namespace }}"
  name: apiserver
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: apiserver-serving-cert
spec:
  selector:
    apiserver: "true"
  ports:
  - port: 443
    targetPort: 8443

