---
# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ kube_system_namespace }}"
  name: "extension-apiserver-authentication-reader-{{ broker_namespace }}"
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  namespace: "{{ broker_namespace }}"
  name: apiserver
