---
# allow the kube service catalog's SA to read the static secret defined
# above, which will contain the token for the SA that can call the TSB.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: templateservicebroker-auth-reader
  namespace: "{{ broker_namespace }}"
rules:
- apiGroups:
  - ""
  resourceNames:
  - templateservicebroker-client
  resources:
  - secrets
  verbs:
  - get
