---
# grant the service account permission to call the TSB
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: templateservicebroker-client
roleRef:
  kind: ClusterRole
  name: system:openshift:templateservicebroker-client
subjects:
- kind: ServiceAccount
  namespace: "{{ broker_namespace }}"
  name: templateservicebroker-client
